name: Slack Notification

on:
  push:

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
    - name: Notify Slack
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        args: >-
          {
            "text": "A new push has been made to the repository",
            "file": "${{ env.GITHUB_WORKSPACE }}/path/to/file",
            "file_type": "auto"
          }




